# Generated by Django 5.2.8 on 2025-11-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='phone',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
